#INCLUDE <P16F628A.INC>
	    
; Configuração dos Fuses bits do microcontrolador
    __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF
        
#DEFINE SENSOR_ESQUERDO	    PORTB,  5
#DEFINE	SENSOR_MEIO	    PORTB,  6
#DEFINE	SENSOR_DIREITO	    PORTB,  7
      
; ESTADOS DE PORTA TAL QUE OCORREM AS SEGUINTES AÇÕES
; ESSES ESTADOS SERÃO INSERIDOS EM PORTA
    
#DEFINE	VIRA_ESQUERDA		b'00000110'	;DEFINE O BYTE DE TAL FORMA QUE O MOTOR DIREITO SEJA ACIONADO
#DEFINE VIRA_ESQUERDA_FRACO	b'00000010'
#DEFINE	FRENTE			b'00001010'	;DEFINE O BYTE DE TAL FORMA QUE AMBOS OS MOTORES SEJAM ACIONADOS
#DEFINE	VIRA_DIREITA		b'00001001'	;DEFINE O BYTE DE TAL FORMA QUE O MOTOR ESQUERDO SEJA ACIONADO
#DEFINE VIRA_DIREITA_FRACO	b'00001000'
    
    
; PINAGEM DA PONTE H
;#DEFINE	INPUT_1		PORTA,	0
;#DEFINE	INPUT_2		PORTA,	1
;#DEFINE	INPUT_3		PORTA,	2
;#DEFINE	INPUT_4		PORTA,	3
    
; FRENTE --> 
	    ;INPUT_1 = 1, MOTOR E FRENTE
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 1, MOTOR D FRENTE
	    ;INPUT_4 = 0
    
; DIREITA --> 
	    ;INPUT_1 = 1, MOTOR E FRENTE
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 0, MOTOR D TRÁS
	    ;INPUT_4 = 1
	    
; DIREITA FRACO --> 
	    ;INPUT_1 = 1, MOTOR E FRENTE
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 0, MOTOR D PARADO
	    ;INPUT_4 = 0
    
; ESQUERDA -->	
	    ;INPUT_1 = 0, MOTOR E TRÁS
	    ;INPUT_2 = 1, 
	    ;INPUT_3 = 1, MOTOR D FRENTE
	    ;INPUT_4 = 0

; ESQUERDA FRACO -->	
	    ;INPUT_1 = 0, MOTOR E PARADO
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 1, MOTOR D FRENTE
	    ;INPUT_4 = 0

    ORG 0x00
    GOTO INICIO

    ORG 0x04
    RETFIE

INICIO:
    BANKSEL TRISA
    CLRF    TRISA
    
    BANKSEL PORTA
    
    CLRF    PORTA
    
    BANKSEL TRISB
    
    MOVLW   0xFF
    MOVWF   TRISB
    
    
LOOP:
    
    ;CLRW
    
    ;LÓGICA SENSOR_ESQUERDO
    
    BANKSEL PORTB
    
    BTFSC   SENSOR_ESQUERDO
    MOVLW   VIRA_ESQUERDA
    
    ;LÓGICA SENSOR DIREITO
    
    BTFSC   SENSOR_DIREITO
    MOVLW   VIRA_DIREITA
    
    BTFSC   SENSOR_MEIO
    CALL    LOGICA_MEIO
    
    BANKSEL PORTA
    
    MOVWF   PORTA
 
    GOTO    LOOP
    
    LOGICA_MEIO
	
	MOVLW	FRENTE
	
	;LÓGICA SENSOR_ESQUERDO
    
	BTFSC   SENSOR_ESQUERDO
	MOVLW   VIRA_ESQUERDA_FRACO
    
	;LÓGICA SENSOR DIREITO
    
	BTFSC   SENSOR_DIREITO
	MOVLW   VIRA_DIREITA_FRACO
	
	RETURN
    
    
    END



