#INCLUDE <P16F628A.INC>
	    
; Configuração dos Fuses bits do microcontrolador
    __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF
    
    
; Configuração PWM 
; PR2 = [(Fosc) / (Fpwm x 4 x PRESCALE_TIMER2)] - 1

    
#DEFINE SENSOR_ESQUERDO	    PORTB,  5
#DEFINE	SENSOR_MEIO	    PORTB,  6
#DEFINE	SENSOR_DIREITO	    PORTB,  7
    
#DEFINE CONTROL_VEL_MOTORE  PORTB,  0
#DEFINE CONTROL_VEL_MOTORD  PORTB,  1
#DEFINE PINO_PWM	    PORTB,  3
    
    
; ESTADOS DE PORTA TAL QUE OCORREM AS SEGUINTES AÇÕES
; ESSES ESTADOS SERÃO INSERIDOS EM PORTA
    
#DEFINE	VIRA_ESQUERDA	b'00000110'	;DEFINE O BYTE DE TAL FORMA QUE O MOTOR DIREITO SEJA ACIONADO
#DEFINE	FRENTE		b'00001010'	;DEFINE O BYTE DE TAL FORMA QUE AMBOS OS MOTORES SEJAM ACIONADOS
#DEFINE	VIRA_DIREITA	b'00001001'	;DEFINE O BYTE DE TAL FORMA QUE O MOTOR ESQUERDO SEJA ACIONADO

    
    
; PINAGEM DA PONTE H
;#DEFINE	INPUT_1		PORTA,	0
;#DEFINE	INPUT_2		PORTA,	1
;#DEFINE	INPUT_3		PORTA,	2
;#DEFINE	INPUT_4		PORTA,	3
    
; FRENTE --> 
	    ;INPUT_1 = 1, 
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 1, 
	    ;INPUT_4 = 0
    
; DIREITA --> 
	    ;INPUT_1 = 1, 
	    ;INPUT_2 = 0, 
	    ;INPUT_3 = 0, 
	    ;INPUT_4 = 1
    
; ESQUERDA -->	
	    ;INPUT_1 = 0, 
	    ;INPUT_2 = 1, 
	    ;INPUT_3 = 1, 
	    ;INPUT_4 = 0

    ORG 0x00
    GOTO INICIO

    ORG 0x04
    RETFIE

INICIO:
    BANKSEL TRISA
    CLRF    TRISA
    
    BANKSEL PORTA
    
    CLRF    PORTA
    
    BANKSEL TRISB
    
    MOVLW   b'11100000'	; Configura RB3 como saída do PWM
    MOVWF   TRISB
    
CONFIG_PWM:		; Gera PWM 10kHz com 50% de Duty Cycle no pino RB3
    
    BANKSEL PR2
    MOVLW d'99'
    MOVWF PR2
    
    BANKSEL CCP1CON
    MOVLW b'00001111'
    MOVWF CCP1CON
    
    BANKSEL CCPR1L
    MOVLW b'00110010'
    MOVWF CCPR1L
    
    BANKSEL T2CON
    MOVLW b'00000100'
    MOVWF T2CON
    
LOOP:
    
    
    
    ;LÓGICA SENSOR_ESQUERDO
    
    BANKSEL PORTB
    
    BTFSC   SENSOR_ESQUERDO
    MOVLW   VIRA_ESQUERDA
    
    ;LÓGICA SENSOR DIREITO
    
    BTFSC   SENSOR_DIREITO
    MOVLW   VIRA_DIREITA
    
    BTFSC   SENSOR_MEIO
    CALL    logica_pwm
    
    BANKSEL PORTA
    
    MOVWF   PORTA
 
    GOTO    LOOP
    
logica_pwm
	
	MOVLW	FRENTE
	
	BTFSC   SENSOR_ESQUERDO
	CALL	sensor_esquerdo_pwm
    
	BTFSC   SENSOR_DIREITO
	CALL	sensor_direto_pwm
	
	; RESTARURA AS VELOCIDADES DOS MOTORES CASO APENAS O SENSOR DO MEIO DETECTE
	
	BTFSC	SENSOR_MEIO
	BCF	CONTROL_VEL_MOTORE
	BTFSC	SENSOR_MEIO
	BCF	CONTROL_VEL_MOTORD
	
	return
	
  
sensor_esquerdo_pwm
	BSF	CONTROL_VEL_MOTORE  ; DIMINUI VELOCIDADE DO MOTOR DIREITO --> CURVA SUAVE PARA A DIREITA
	
	return
    
sensor_direto_pwm
	BSF	CONTROL_VEL_MOTORE  ; DIMINUI VELOCIDADE DO MOTOR ESQUERDO --> CURVA SUAVE PARA A ESQUERDA
	
	return
    
    
    END



